# You have to replace <ENTITY_PORT_NAME_xxx> with the name of the Output port
# of your top entity
set_location_assignment PIN_M22  -to <ENTITY_PORT_NAME_CONNECTED_TO_HSYNC>
set_location_assignment PIN_M21  -to <ENTITY_PORT_NAME_CONNECTED_TO_VSYNC>
set_location_assignment PIN_B20  -to <ENTITY_PORT_NAME_CONNECTED_TO_DAC_CLK>
set_location_assignment PIN_K17  -to <ENTITY_PORT_NAME_CONNECTED_TO_RED[0]>
set_location_assignment PIN_K18  -to <ENTITY_PORT_NAME_CONNECTED_TO_RED[1]>
set_location_assignment PIN_D20  -to <ENTITY_PORT_NAME_CONNECTED_TO_RED[2]>
set_location_assignment PIN_F19  -to <ENTITY_PORT_NAME_CONNECTED_TO_RED[3]>
set_location_assignment PIN_H19  -to <ENTITY_PORT_NAME_CONNECTED_TO_RED[4]>
set_location_assignment PIN_H20  -to <ENTITY_PORT_NAME_CONNECTED_TO_RED[5]>
set_location_assignment PIN_K19  -to <ENTITY_PORT_NAME_CONNECTED_TO_RED[6]>
set_location_assignment PIN_C21  -to <ENTITY_PORT_NAME_CONNECTED_TO_RED[7]>
set_location_assignment PIN_C22  -to <ENTITY_PORT_NAME_CONNECTED_TO_RED[8]>
set_location_assignment PIN_D21  -to <ENTITY_PORT_NAME_CONNECTED_TO_RED[9]>
set_location_assignment PIN_L22  -to <ENTITY_PORT_NAME_CONNECTED_TO_GREEN[0]>
set_location_assignment PIN_L21  -to <ENTITY_PORT_NAME_CONNECTED_TO_GREEN[1]>
set_location_assignment PIN_K21  -to <ENTITY_PORT_NAME_CONNECTED_TO_GREEN[2]>
set_location_assignment PIN_J22  -to <ENTITY_PORT_NAME_CONNECTED_TO_GREEN[3]>
set_location_assignment PIN_J21  -to <ENTITY_PORT_NAME_CONNECTED_TO_GREEN[4]>
set_location_assignment PIN_H22  -to <ENTITY_PORT_NAME_CONNECTED_TO_GREEN[5]>
set_location_assignment PIN_H21  -to <ENTITY_PORT_NAME_CONNECTED_TO_GREEN[6]>
set_location_assignment PIN_F22  -to <ENTITY_PORT_NAME_CONNECTED_TO_GREEN[7]>
set_location_assignment PIN_F21  -to <ENTITY_PORT_NAME_CONNECTED_TO_GREEN[8]>
set_location_assignment PIN_D22  -to <ENTITY_PORT_NAME_CONNECTED_TO_GREEN[9]>
set_location_assignment PIN_J18  -to <ENTITY_PORT_NAME_CONNECTED_TO_BLUE[0]>
set_location_assignment PIN_J17  -to <ENTITY_PORT_NAME_CONNECTED_TO_BLUE[1]>
set_location_assignment PIN_H18  -to <ENTITY_PORT_NAME_CONNECTED_TO_BLUE[2]>
set_location_assignment PIN_H17  -to <ENTITY_PORT_NAME_CONNECTED_TO_BLUE[3]>
set_location_assignment PIN_G17  -to <ENTITY_PORT_NAME_CONNECTED_TO_BLUE[4]>
set_location_assignment PIN_F17  -to <ENTITY_PORT_NAME_CONNECTED_TO_BLUE[5]>
set_location_assignment PIN_H16  -to <ENTITY_PORT_NAME_CONNECTED_TO_BLUE[6]>
set_location_assignment PIN_A20  -to <ENTITY_PORT_NAME_CONNECTED_TO_BLUE[7]>
set_location_assignment PIN_B19  -to <ENTITY_PORT_NAME_CONNECTED_TO_BLUE[8]>
set_location_assignment PIN_A19  -to <ENTITY_PORT_NAME_CONNECTED_TO_BLUE[9]>
