# TCL File Generated by Component Editor 17.0
# Sun Oct 29 10:04:36 CET 2017
# DO NOT MODIFY


# 
# LCD_8080_Slave "LCD_8080_Slave" v1.5
# Mario Fischer 2017.10.29.10:04:36
# LCD Avalon Slave with 8080 Parallel Interface
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module LCD_8080_Slave
# 
set_module_property DESCRIPTION "LCD Avalon Slave with 8080 Parallel Interface"
set_module_property NAME LCD_8080_Slave
set_module_property VERSION 1.5
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Mario Fischer"
set_module_property DISPLAY_NAME LCD_8080_Slave
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ctrl_lcd_avalonSlave
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ctrl_lcd_avalonslave.vhd VHDL PATH IPCores/LCDCtrl/ctrl_lcd_avalonslave.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file ctrl_lcd_avalonslave.vhd VHDL PATH IPCores/LCDCtrl/ctrl_lcd_avalonslave.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 1
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 avs_WaitRequest waitrequest Output 1
add_interface_port avalon_slave_0 avs_Address_DI address Input 2
add_interface_port avalon_slave_0 avs_WriteData_DI writedata Input 16
add_interface_port avalon_slave_0 avs_ReadData_DO readdata Output 16
add_interface_port avalon_slave_0 avs_Read_SI read Input 1
add_interface_port avalon_slave_0 avs_Write_SI write Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink Clk_CI clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink Reset_RI reset Input 1


# 
# connection point lcd_interface
# 
add_interface lcd_interface conduit end
set_interface_property lcd_interface associatedClock clock_sink
set_interface_property lcd_interface associatedReset reset_sink
set_interface_property lcd_interface ENABLED true
set_interface_property lcd_interface EXPORT_OF ""
set_interface_property lcd_interface PORT_NAME_MAP ""
set_interface_property lcd_interface CMSIS_SVD_VARIABLES ""
set_interface_property lcd_interface SVD_ADDRESS_GROUP ""

add_interface_port lcd_interface lcd_ChipSelect_n_SO lcd_chipselect_n_so Output 1
add_interface_port lcd_interface lcd_DataCommand_SO lcd_datacommand_so Output 1
add_interface_port lcd_interface lcd_Data_DIO lcd_data_dio Bidir 16
add_interface_port lcd_interface lcd_Read_n_SO lcd_read_n_so Output 1
add_interface_port lcd_interface lcd_Reset_n_SO lcd_reset_n_so Output 1
add_interface_port lcd_interface lcd_Write_n_SO lcd_write_n_so Output 1
add_interface_port lcd_interface lcd_im0_SO lcd_im0_so Output 1

